<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE table
[
<!ELEMENT table (team+)>
<!ELEMENT team (position,name,totalPoints,homePoints,awayPoints,matchesPlayed,homeMatchesPlayed,awayMatchesPlayed,wins,homeWins,awayWins,draws,homeDraws,awayDraws,losses,homeLosses,awayLosses,goalsFor,homeGoalsFor,awayGoalsFor,goalsAgainst,homeGoalsAgainst,awayGoalsAgainst)>
<!ELEMENT position (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT totalPoints (#PCDATA)>
<!ELEMENT matchesPlayed (#PCDATA)>
<!ELEMENT wins (#PCDATA)>
<!ELEMENT draws (#PCDATA)>
<!ELEMENT losses (#PCDATA)>
<!ELEMENT goalsFor (#PCDATA)>
<!ELEMENT goalsAgainst (#PCDATA)>
]>
<table>
  <team>
    <position>1</position>
    <name>M. City</name>
    <totalPoints>89</totalPoints>
    <matchesPlayed>38</matchesPlayed>
    <wins>28</wins>
    <draws>5</draws>
    <losses>5</losses>
    <goalsFor>94</goalsFor>
    <goalsAgainst>33</goalsAgainst>
  </team>
  <team>
    <position>2</position>
    <name>Arsenal</name>
    <totalPoints>84</totalPoints>
    <matchesPlayed>38</matchesPlayed>
    <wins>26</wins>
    <draws>6</draws>
    <losses>6</losses>
    <goalsFor>88</goalsFor>
    <goalsAgainst>43</goalsAgainst>
  </team>
  <team>
    <position>3</position>
    <name>M. United</name>
    <totalPoints>75</totalPoints>
    <matchesPlayed>38</matchesPlayed>
    <wins>23</wins>
    <draws>6</draws>
    <losses>9</losses>
    <goalsFor>58</goalsFor>
    <goalsAgainst>43</goalsAgainst>
  </team>
  <team>
    <position>4</position>
    <name>Newcastle</name>
    <totalPoints>71</totalPoints>
    <matchesPlayed>38</matchesPlayed>
    <wins>19</wins>
    <draws>14</draws>
    <losses>5</losses>
    <goalsFor>68</goalsFor>
    <goalsAgainst>33</goalsAgainst>
  </team>
  <team>
    <position>5</position>
    <name>Liverpool</name>
    <totalPoints>67</totalPoints>
    <matchesPlayed>38</matchesPlayed>
    <wins>19</wins>
    <draws>10</draws>
    <losses>9</losses>
    <goalsFor>75</goalsFor>
    <goalsAgainst>47</goalsAgainst>
  </team>
  <team>
    <position>6</position>
    <name>Brighton</name>
    <totalPoints>62</totalPoints>
    <matchesPlayed>38</matchesPlayed>
    <wins>18</wins>
    <draws>8</draws>
    <losses>12</losses>
    <goalsFor>72</goalsFor>
    <goalsAgainst>53</goalsAgainst>
  </team>
  <team>
    <position>7</position>
    <name>Aston Villa</name>
    <totalPoints>61</totalPoints>
    <matchesPlayed>38</matchesPlayed>
    <wins>18</wins>
    <draws>7</draws>
    <losses>13</losses>
    <goalsFor>51</goalsFor>
    <goalsAgainst>46</goalsAgainst>
  </team>
  <team>
    <position>8</position>
    <name>Tottenham</name>
    <totalPoints>60</totalPoints>
    <matchesPlayed>38</matchesPlayed>
    <wins>18</wins>
    <draws>6</draws>
    <losses>14</losses>
    <goalsFor>69</goalsFor>
    <goalsAgainst>63</goalsAgainst>
  </team>
  <team>
    <position>9</position>
    <name>Brentford</name>
    <totalPoints>59</totalPoints>
    <matchesPlayed>38</matchesPlayed>
    <wins>15</wins>
    <draws>14</draws>
    <losses>9</losses>
    <goalsFor>58</goalsFor>
    <goalsAgainst>46</goalsAgainst>
  </team>
  <team>
    <position>10</position>
    <name>Leeds United</name>
    <totalPoints>58</totalPoints>
    <matchesPlayed>38</matchesPlayed>
    <wins>15</wins>
    <draws>13</draws>
    <losses>10</losses>
    <goalsFor>62</goalsFor>
    <goalsAgainst>54</goalsAgainst>
  </team>
  <team>
    <position>11</position>
    <name>Everton</name>
    <totalPoints>54</totalPoints>
    <matchesPlayed>38</matchesPlayed>
    <wins>14</wins>
    <draws>12</draws>
    <losses>12</losses>
    <goalsFor>55</goalsFor>
    <goalsAgainst>46</goalsAgainst>
  </team>
  <team>
    <position>12</position>
    <name>Leicester City</name>
    <totalPoints>53</totalPoints>
    <matchesPlayed>38</matchesPlayed>
    <wins>15</wins>
    <draws>8</draws>
    <losses>15</losses>
    <goalsFor>56</goalsFor>
    <goalsAgainst>54</goalsAgainst>
  </team>
  <team>
    <position>13</position>
    <name>West Ham</name>
    <totalPoints>51</totalPoints>
    <matchesPlayed>38</matchesPlayed>
    <wins>14</wins>
    <draws>9</draws>
    <losses>15</losses>
    <goalsFor>55</goalsFor>
    <goalsAgainst>52</goalsAgainst>
  </team>
  <team>
    <position>14</position>
    <name>Wolves</name>
    <totalPoints>50</totalPoints>
    <matchesPlayed>38</matchesPlayed>
    <wins>12</wins>
    <draws>14</draws>
    <losses>12</losses>
    <goalsFor>44</goalsFor>
    <goalsAgainst>46</goalsAgainst>
  </team>
  <team>
    <position>15</position>
    <name>Crystal Palace</name>
    <totalPoints>49</totalPoints>
    <matchesPlayed>38</matchesPlayed>
    <wins>13</wins>
    <draws>10</draws>
    <losses>15</losses>
    <goalsFor>41</goalsFor>
    <goalsAgainst>46</goalsAgainst>
  </team>
  <team>
    <position>16</position>
    <name>Southampton</name>
    <totalPoints>46</totalPoints>
    <matchesPlayed>38</matchesPlayed>
    <wins>12</wins>
    <draws>10</draws>
    <losses>16</losses>
    <goalsFor>44</goalsFor>
    <goalsAgainst>49</goalsAgainst>
  </team>
  <team>
    <position>17</position>
    <name>Norwich City</name>
    <totalPoints>44</totalPoints>
    <matchesPlayed>38</matchesPlayed>
    <wins>11</wins>
    <draws>11</draws>
    <losses>16</losses>
    <goalsFor>43</goalsFor>
    <goalsAgainst>56</goalsAgainst>
  </team>
  <team>
    <position>18</position>
    <name>Watford</name>
    <totalPoints>38</totalPoints>
    <matchesPlayed>38</matchesPlayed>
    <wins>9</wins>
    <draws>11</draws>
    <losses>18</losses>
    <goalsFor>37</goalsFor>
    <goalsAgainst>55</goalsAgainst>
  </team>
  <team>
    <position>19</position>
    <name>Burnley</name>
    <totalPoints>37</totalPoints>
    <matchesPlayed>38</matchesPlayed>
    <wins>10</wins>
    <draws>7</draws>
    <losses>21</losses>
    <goalsFor>33</goalsFor>
    <goalsAgainst>55</goalsAgainst>
  </team>
  <team>
    <position>20</position>
    <name>Newcastle United</name>
    <totalPoints>35</totalPoints>
    <matchesPlayed>38</matchesPlayed>
    <wins>8</wins>
    <draws>11</draws>
    <losses>19</losses>
    <goalsFor>34</goalsFor>
    <goalsAgainst>65</goalsAgainst>
  </team>
</table>
